sproject/main/urls.py

from django.urls import path, include
from .views import *

app_name = 'main'


urlpatterns = [
    path('', index, name = 'index'),
    path('registration', registration, name = 'registration'),
    path('page_6', page_6, name = 'page_6'),
    path('auth', auth, name = 'auth'),
    path('lobby', lobby, name = 'lobby'),
    path('test', test, name = 'test'),
    path('page_1', page_1, name = 'page_1'),
    path('page_2', page_2, name = 'page_2'),
    path('page_3', page_3, name = 'page_3'),
    path('page_4', page_4, name = 'page_4'),
    path('page_5', page_5, name = 'page_5'), 
    path('logout', logout_user, name = 'logout')
]

sproject/sproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

sproject/main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserAccount(models.Model): 
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    is_done_test = models.BooleanField(null = True)
    test_mark = models.IntegerField(null = True) 

sproject/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import *

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'u-border-no-left u-border-no-right u-border-no-top u-border-white u-input u-input-rectangle u-none', 'placeholder': 'Введите логин '}))
    name = forms.CharField(label = 'Имя и Фамилия', widget = forms.TextInput(attrs={'class': 'u-border-no-left u-border-no-right u-border-no-top u-border-white u-input u-input-rectangle u-none', 'placeholder': 'Введите имя и фамилию '}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'u-border-no-left u-border-no-right u-border-no-top u-border-white u-input u-input-rectangle u-none', 'placeholder': 'Введите email'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'u-border-no-left u-border-no-right u-border-no-top u-border-white u-input u-input-rectangle u-none', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'u-border-no-left u-border-no-right u-border-no-top u-border-white u-input u-input-rectangle u-none', 'placeholder': 'Введите пароль еще раз '}))

    class Meta:
        model = User
        fields = ('username', 'name', 'email', 'password1', 'password2')


class LoginUserForm(forms.Form):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'u-border-no-left u-border-no-right u-border-no-top u-border-white u-input u-input-rectangle u-none', 'placeholder': 'Введите логин'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'u-border-no-left u-border-no-right u-border-no-top u-border-white u-input u-input-rectangle u-none', 'placeholder': 'Введите пароль'}))
    

class TestForm(forms.Form): 
    CHOICES =( 
    ("1", "One"), 
    ("2", "Two"), 
    ("3", "Three"), 
    ("4", "Four"), 
    ("5", "Five"),) 

    q1 = forms.ChoiceField(choices= CHOICES,  widget = forms.CheckboxSelectMultiple())
    


sproject/main/views.py
from django.shortcuts import render, redirect
from .forms import RegisterUserForm, LoginUserForm, TestForm
from django.contrib.auth import authenticate
from django.contrib.auth import logout, login
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import UserAccount
from django.urls import reverse_lazy

# Create your views here.
def index(request): 
    return render(request, 'main/index.html')

def auth(request):
    if request.method == 'POST':
        form = LoginUserForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('/lobby')
                else:
                    return HttpResponse('Disabled account')
            else:
                print('Access denied')
                return render(request, 'main/login.html', {'form': form, 'access_denied': True})
        else: 
            print(form.errors)
    else:
        form = LoginUserForm()

    return render(request, 'main/auth.html', {'form': form})   

@login_required(login_url='/register')
def test(request): 


    if request.method == 'POST':

        form = TestForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            print(data)
        else: 
            print(form.errors)
    else:
        form = RegisterUserForm()  

    return render(request, 'main/test.html', {'form': TestForm})

def registration(request): 
    if request.method == 'POST':
        user_form = RegisterUserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.first_name = user_form.cleaned_data['name']
            user.save()
            user_acc = UserAccount(user=user)
            user_acc.save()
            login(request, user)
            return redirect('/lobby')
    else:
        user_form = RegisterUserForm()  
    return render(request, 'main/registration.html', {'form': user_form})

@login_required(login_url=reverse_lazy('main:auth'), redirect_field_name=None)
def page_1(request): 
    next_page = 2
    return render(request, 'main/page_1.html', {'page_num': next_page})

@login_required(login_url=reverse_lazy('main:auth'), redirect_field_name=None)
def page_2(request): 
    next_page = 3
    prev_page = 1
    return render(request, 'main/page_2.html', {'page_num': next_page, "prev_page": prev_page})

@login_required(login_url=reverse_lazy('main:auth'), redirect_field_name=None)
def page_3(request): 
    next_page = 4
    prev_page = 2
    return render(request, 'main/page_3.html', {'page_num': next_page, "prev_page": prev_page})

@login_required(login_url=reverse_lazy('main:auth'), redirect_field_name=None)
def page_4(request): 
    next_page = 5
    prev_page = 3
    return render(request, 'main/page_4.html', {'page_num': next_page, "prev_page": prev_page})

@login_required(login_url=reverse_lazy('main:auth'), redirect_field_name=None)
def page_5(request): 
    next_page = 6
    prev_page = 4
    return render(request, 'main/page_5.html', {'page_num': next_page, "prev_page": prev_page})

@login_required(login_url=reverse_lazy('main:auth'), redirect_field_name=None)
def page_6(request): 
    next_page = 6
    prev_page = 5
    return render(request, 'main/page_6.html', {'page_num': next_page, "prev_page": prev_page})

def bad_res(request): 
    return render(request, 'main/test.html')

def good_res(request): 
    return render(request, 'main/test.html')

@login_required(login_url=reverse_lazy('main:auth'), redirect_field_name=None)
def lobby(request): 
    return render(request, 'main/lobby.html')


def logout_user(request):
    logout(request)
    return redirect('/auth')

sproject/main/templates/main/lobby.html
{%load static%}
<!DOCTYPE html>
<html style="font-size: 16px;" lang="ru"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Mobile App Development, ​Stimulate your cognitive abilities while having fun, What We Do, Testimonials, Company Services, ​Love the way you work together?, Our Portfolio, About Us, ​Our way, Get in Touch, ​Level up your brand">
    <meta name="description" content="">
    <title>lobby</title>
    <link rel="stylesheet" href="{%static 'main/css/main.css'%}" media="screen">
    <link rel="stylesheet" href="{%static 'main/css/lobby.css'%}" media="screen">
    <script class="u-script" type="text/javascript" src="{%static 'main/js/jquery.js'%}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{%static 'main/js/main.js'%}" defer=""></script>
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
    

    <meta name="theme-color" content="#a37fdf">
    <meta property="og:title" content="lobby">
    <meta property="og:type" content="website">
  <meta data-intl-tel-input-cdn-path="intlTelInput/"></head>
  <body style = "background-color: black;"data-path-to-root="./" data-include-products="false" class="u-body u-xl-mode" data-lang="ru"><header class="u-black u-border-2 u-border-no-left u-border-no-right u-border-no-top u-border-palette-1-base u-clearfix u-header u-header" id="sec-d402"><div class="u-clearfix u-sheet u-sheet-1">
        <nav class="u-menu u-menu-hamburger u-offcanvas u-menu-1" data-responsive-from="XL">
          <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px; font-weight: 700; text-transform: uppercase;">
            <a class="u-button-style u-custom-active-border-color u-custom-border u-custom-border-color u-custom-borders u-custom-hover-border-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
              <svg class="u-svg-link" viewBox="0 0 24 24"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
              <svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><g><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>
</g></svg>
            </a>
          </div>
          <div class="u-nav-container">
            <ul class="u-nav u-spacing-30 u-unstyled u-nav-1"><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'main:index'%}" style="padding: 10px 0px;">Главная</a>
            </li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'main:registration' %}" style="padding: 10px 0px;">Регистрация</a>
            </li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'main:auth' %}" style="padding: 10px 0px;">Войти</a>
            </li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'main:lobby' %}" style="padding: 10px 0px;">Меню</a>
            </li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'main:page_1' %}" style="padding: 10px 0px;">Введение</a>
            </li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'main:page_2' %}" style="padding: 10px 0px;">Вирусы/Трояны</a>
            </li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'main:page_3' %}" style="padding: 10px 0px;">Фишинг</a>
            </li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'main:page_4' %}" style="padding: 10px 0px;">Рекламное ПО</a>
            </li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'main:page_5' %}" style="padding: 10px 0px;">Социальная инженерия</a>
            </li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'main:page_6' %}" style="padding: 10px 0px;">Заключение</a>
            </li></ul>
          </div>
          <div class="u-nav-container-collapse">
            <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
              <div class="u-inner-container-layout u-sidenav-overflow">
                <div class="u-menu-close"></div>
                <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:index'%}">Главная</a>
                </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:registration'%}">Регистрация</a>
                </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:auth' %}">Войти</a>
                </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:lobby' %}">Меню</a>
                </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:page_1' %}">Введение</a>
                </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:page_2' %}">Вирусы/Трояны</a>
                </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:page_3' %}">Фишинг</a>
                </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:page_4' %}">Рекламное ПО</a>
                </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:page_5' %}">Социальная инженерия</a>
                </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'main:page_6' %}">Заключение</a>
                </li></ul>
              </div>
            </div>
            <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
          </div>
        </nav>
        <a href="/" class="u-image u-logo u-image-1" data-image-width="281" data-image-height="239">
          <img src="{%static 'main/img/image1.png'%}" class="u-logo-image u-logo-image-1">
        </a>
      </div></header>
    <section class="u-align-center u-clearfix u-palette-5-base u-section-1" id="carousel_d2df">
      <h2 class="u-text u-text-default u-text-1">{{ request.user.first_name }}</h2>
      <p class="u-text u-text-default-lg u-text-default-xl u-text-2">Sample text. Click to select the text box. Click again or double click to start editing the text.&nbsp;Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu . </p>
      <div class="u-expanded-width u-palette-1-base u-shape u-shape-rectangle u-shape-1"></div>
      <div class="u-list u-list-1">
        <div class="u-repeater u-repeater-1">
          <div class="u-align-center u-container-style u-list-item u-radius-10 u-repeater-item u-shape-round u-white u-list-item-1">
            <div class="u-container-layout u-similar-container u-valign-bottom u-container-layout-1">
              <img alt="" class="u-expanded-width u-image u-image-contain u-image-default u-image-1" data-image-width="700" data-image-height="500" src="{%static 'main/img/11.png'%}">
              <h4 class="u-text u-text-default u-text-palette-1-base u-text-3">К курсу</h4>
              <p class="u-text u-text-4">Перейти к курсу</p>
              <a href="{% url 'main:page_1'%}" class="u-active-palette-2-light-1 u-align-left u-btn u-btn-round u-button-style u-custom-font u-font-raleway u-hover-palette-2-light-1 u-palette-1-base u-radius-10 u-text-body-alt-color u-btn-1" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">НАЧАТЬ</a>
            </div>
          </div>
          <div class="u-align-center u-container-style u-list-item u-radius-10 u-repeater-item u-shape-round u-white u-list-item-2">
            <div class="u-container-layout u-similar-container u-valign-bottom u-container-layout-2">
              <img alt="" class="u-expanded-width u-image u-image-contain u-image-default u-image-2" data-image-width="512" data-image-height="512" src="{%static 'main/img/image-4.png'%}">
              <h4 class="u-text u-text-default u-text-palette-1-base u-text-5">Получить сертификат</h4>
              <p class="u-text u-text-6">Получить сертификат, после прохождения курса</p>
              <a href="https://nicepage.cc" class="u-active-palette-2-light-1 u-align-left u-btn u-btn-round u-button-style u-custom-font u-font-raleway u-hover-palette-2-light-1 u-palette-1-base u-radius-10 u-text-body-alt-color u-btn-2" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">ПОЛУЧИТЬ</a>
            </div>
          </div>
          <div class="u-align-center u-container-style u-list-item u-radius-10 u-repeater-item u-shape-round u-white u-list-item-3">
            <div class="u-container-layout u-similar-container u-valign-bottom u-container-layout-3">
              <img alt="" class="u-expanded-width u-image u-image-contain u-image-default u-image-3" data-image-width="512" data-image-height="512" src="{%static 'main/img/image-5.png'%}">
              <h4 class="u-text u-text-default u-text-palette-1-base u-text-7">Выход</h4>
              <p class="u-text u-text-8">Выйти из аккаунта</p>
              <a href="{% url 'main:logout'%}" class="u-active-palette-2-light-1 u-align-left u-btn u-btn-round u-button-style u-custom-font u-font-raleway u-hover-palette-2-light-1 u-palette-1-base u-radius-10 u-text-body-alt-color u-btn-3" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">ВЫЙТИ</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    
  
</body></html>